"""empty message

Revision ID: ed881601f1ff
Revises: 1fa6bba580d3
Create Date: 2024-09-27 15:43:33.884696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed881601f1ff'
down_revision = '1fa6bba580d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exploit_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fix_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_column('fix_info')
        batch_op.drop_column('exploit_info')

    # ### end Alembic commands ###
